<!--
 * @Description:
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2021-02-05 16:11:44
 * @LastEditors: Luan Feng
 * @LastEditTime: 2021-02-08 11:13:33
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div v-loading="loading" id="china_map_box">
    <div :id="chartID"/>
  </div>
</template>

<script>
import echarts from 'echarts'
import 'echarts/map/js/china.js'
// import 'echarts/map/js/province/anhui.js'
// import 'echarts/map/js/province/aomen.js'
// import 'echarts/map/js/province/beijing.js'
// import 'echarts/map/js/province/chongqing.js'
// import 'echarts/map/js/province/fujian.js'
// import 'echarts/map/js/province/gansu.js'
// import 'echarts/map/js/province/guangdong.js'
// import 'echarts/map/js/province/guangxi.js'
// import 'echarts/map/js/province/guizhou.js'
// import 'echarts/map/js/province/hainan.js'
// import 'echarts/map/js/province/hebei.js'
// import 'echarts/map/js/province/heilongjiang.js'
// import 'echarts/map/js/province/henan.js'
// import 'echarts/map/js/province/jiangsu.js'
// import 'echarts/map/js/province/jiangxi.js'
// import 'echarts/map/js/province/jilin.js'
// import 'echarts/map/js/province/liaoning.js'
// import 'echarts/map/js/province/neimenggu.js'
// import 'echarts/map/js/province/ningxia.js'
// import 'echarts/map/js/province/qinghai.js'
// import 'echarts/map/js/province/shandong.js'
// import 'echarts/map/js/province/shanghai.js'
// import 'echarts/map/js/province/shanxi.js'
// import 'echarts/map/js/province/sichuan.js'
// import 'echarts/map/js/province/taiwan.js'
// import 'echarts/map/js/province/tianjin.js'
// import 'echarts/map/js/province/xianggang.js'
// import 'echarts/map/js/province/xizang.js'
// import 'echarts/map/js/province/xinjiang.js'
// import 'echarts/map/js/province/yunnan.js'
// import 'echarts/map/js/province/zhejiang.js'

export default {
  data() {
    return {
      chart: null,
      // echart 配制option
      mapOption: null,
      loading: false,
      // echart data
      dataList: [
        {
          name: '南海诸岛',
          value: 100,
          code: 'nanhaizhudao'
        },
        {
          name: '北京',
          region: '张北区域',
          value: 0,
          code: 'beijing'
        },
        {
          name: '天津',
          region: '张北区域',
          value: 0
        },
        {
          name: '上海',
          region: '张北区域',
          value: 1
        },
        {
          name: '重庆',
          region: '张北区域',
          value: 2
        },
        {
          name: '河北',
          value: '张北区域',
          amount: 0
        },
        {
          name: '河南',
          region: '华中区域',
          value: 3
        },
        {
          name: '云南',
          region: '华南区域',
          value: 4
        },
        {
          name: '辽宁',
          region: '华北区域',
          value: 5
        },
        {
          name: '黑龙江',
          region: '东北区域',
          value: 6,
          code: 'heilongjiang'
        },
        {
          name: '湖南',
          value: 690
        },
        {
          name: '安徽',
          value: 60
        },
        {
          name: '山东',
          value: 39,
          code: 'shandong'
        },
        {
          name: '新疆',
          value: 4
        },
        {
          name: '江苏',
          value: 31
        },
        {
          name: '浙江',
          value: 104
        },
        {
          name: '江西',
          value: 36
        },
        {
          name: '湖北',
          value: 52
        },
        {
          name: '广西',
          value: 33
        },
        {
          name: '甘肃',
          value: 7
        },
        {
          name: '山西',
          value: 5
        },
        {
          name: '内蒙古',
          value: 778
        },
        {
          name: '陕西',
          value: 22
        },
        {
          name: '吉林',
          value: 4
        },
        {
          name: '福建',
          value: 18
        },
        {
          name: '贵州',
          value: 5
        },
        {
          name: '广东',
          value: 98
        },
        {
          name: '青海',
          value: 0
        },
        {
          name: '西藏',
          value: 0
        },
        {
          name: '四川',
          value: 44
        },
        {
          name: '宁夏',
          value: 4
        },
        {
          name: '海南',
          value: 22
        },
        {
          name: '台湾',
          value: 3
        },
        {
          name: '香港',
          value: 5
        },
        {
          name: '澳门',
          value: 555
        }
      ]
    }
  },
  computed: {
    chartID() {
      return `chart_${this._uid}`
    }
  },
  mounted() {
    this.initEchartMap('china')
  },
  methods: {
    getProvinceColor(name) {
      let color = '#333'
      if (['新疆', '吉林', '江苏', '江西', '广西'].indexOf(name) >= 0) {
        color = '#2B5BD6'
      } else if (['内蒙古', '河南', '湖南', '上海', '海南'].indexOf(name) >= 0) {
        color = '#F1446C'
      } else if (['黑龙江', '河北', '安徽', '西藏', '台湾'].indexOf(name) >= 0) {
        color = '#53D3C3'
      } else if (['青海', '北京', '山东', '浙江', '云南'].indexOf(name) >= 0) {
        color = '#FFCB63'
      } else if (['甘肃', '山西', '天津', '重庆'].indexOf(name) >= 0) {
        color = '#082F90'
      } else if (['宁夏', '陕西', '贵州', '广东'].indexOf(name) >= 0) {
        color = '#75C9F3'
      } else if (['辽宁', '四川', '湖北', '福建'].indexOf(name) >= 0) {
        color = '#865EE5'
      }
      return color
    },
    // 初始化中国地图
    initEchartMap(name) {
      this.loading = true
      if (this.chart) {
        this.chart.dispose()
      }
      const mapDiv = this.$el.querySelector(`#${this.chartID}`)
      this.chart = echarts.init(mapDiv)
      this.setMapOption(name)
      this.setMapData()
      this.chart.setOption(this.mapOption)
      // 钻取事件
      this.bindDrillDown()
      this.loading = false
    },
    // 点击钻取下级
    bindDrillDown() {
      this.chart.on('click', params => {
        if (params.seriesType === 'map') {
          if (params.data.code) {
            const drilldownParam = { ...params.data }
            drilldownParam.color = this.getProvinceColor(drilldownParam.name)
            this.$emit('drilldown', drilldownParam)
            // const jsonMap = require(`echarts/map/json/province/${code}.json`)
            // const existsMap = echarts.getMap(name)
            // if (!existsMap) {
            //   echarts.registerMap(name, jsonMap)
            // }
          }
        }
      })
    },
    // 修改echart配制
    setMapData() {
      this.mapOption.series[0]['data'] = this.dataList
    },
    // 切换配置
    setMapOption(name) {
      // '#865EE5', '#53D3C3', '#FFCB63'
      // const proviceColors = { '张北区域': '#F1446C',
      //   '华中区域': '#2B5BD6',
      //   '东北区域': '#FFCB63' }
      // function getColor(p) {
      //   return proviceColors[p.region] || '#eee'
      // }
      // const legendPieces = [{
      //   min: 0,
      //   max: 2,
      //   label: '张北区域',
      //   color: 'red'
      // }]
      const customSettings = []
      this.dataList.forEach((item, index) => {
        // if (legendPieces.findIndex(c => c.value === item.value) === -1 && item.value > 2) {
        //   legendPieces.push({
        //     value: item.value,
        //     label: `${item.region}:${item.name}`,
        //     color: getColor(item)
        //   })
        // }
        const color = item.value ? this.getProvinceColor(item.name) : '#fff'
        customSettings.push({
          name: item.name,
          itemStyle: {
            color: color,
            areaColor: color,
            opacity: 0.4
          },
          emphasis: {
            itemStyle: {
              areaColor: color,
              opacity: 1
            }
          }
        })
      })
      const options = {
        tooltip: {
          triggerOn: 'mousemove', // mousemove、click
          padding: 8,
          borderWidth: 1,
          borderColor: '#409eff',
          backgroundColor: 'rgba(255,255,255,0.7)',
          textStyle: {
            color: '#000000',
            fontSize: 13
          },
          formatter: function(e, t, n) {
            const data = e.data
            // // 模拟数据
            // data.specialImportant = Math.random() * 1000 | 0
            // data.import = Math.random() * 1000 | 0
            // data.compare = Math.random() * 1000 | 0
            // data.common = Math.random() * 1000 | 0
            // data.specail = Math.random() * 1000 | 0

            // const context = `
            //    <div>
            //        <p><b style="font-size:15px;">${data.name}</b>(2020年第一季度)</p>
            //        <p class="tooltip_style"><span class="tooltip_left">事件总数</span><span class="tooltip_right">${data.value}</span></p>
            //        <p class="tooltip_style"><span class="tooltip_left">特别重大事件</span><span class="tooltip_right">${data.specialImportant}</span></p>
            //        <p class="tooltip_style"><span class="tooltip_left">重大事件</span><span class="tooltip_right">${data.import}</span></p>
            //        <p class="tooltip_style"><span class="tooltip_left">较大事件</span><span class="tooltip_right">${data.compare}</span></p>
            //        <p class="tooltip_style"><span class="tooltip_left">一般事件</span><span class="tooltip_right">${data.common}</span></p>
            //        <p class="tooltip_style"><span class="tooltip_left">特写事件</span><span class="tooltip_right">${data.specail}</span></p>
            //    </div>
            // `
            return data.name
          }
        },
        // visualMap: {
        //   show: true,
        //   left: 26,
        //   bottom: 40,
        //   showLabel: true,
        //   type: 'piecewise',
        //   pieces: legendPieces
        //   // splitList: [
        //   //   { start: 500, end: 600 }, { start: 400, end: 500 },
        //   //   { start: 300, end: 400 }, { start: 200, end: 300 },
        //   //   { start: 100, end: 200 }, { start: 0, end: 100 }
        //   // ],
        //   // color: ['#5475f5', '#9feaa5', '#85daef', '#74e2ca', '#e6ac53', '#9fb5ea']
        // },
        geo: {
          map: 'china',
          scaleLimit: {
            min: 1,
            max: 2
          },
          zoom: 1,
          top: 30,
          label: {
            normal: {
              show: true,
              fontSize: 12,
              color: '#333'
            }
          },
          // itemStyle: {
          //   borderColor: 'rgba(0, 0, 0, 0.2)',
          //   opacity: 0.6
          //   // areaColor: '#eee'
          // },
          // emphasis: {
          //   itemStyle: {
          //     borderColor: 'rgba(0,0,0,1)',
          //     opacity: 1
          //   }
          // },
          regions: customSettings
        },
        series: [
          {
            name: '突发事件',
            type: 'map',
            geoIndex: 0,
            // showLegendSymbol: true,
            data: []
          }
        ]
      }
      this.mapOption = options
    }
  }
}
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
  #china_map_box {
      height: 100%;
      position: relative;
      &>div{
        height: 100%;
      }
  }
</style>
