<!--
 * @Description:
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2021-02-08 09:42:02
 * @LastEditors: Luan Feng
 * @LastEditTime: 2021-02-08 11:16:02
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div v-loading="loading" id="province_map_box">
    <div style="position:absolute;top:0;left:0;z-index:10;height:32px;">
      <el-button size="small" @click="backToChinaMap">返回</el-button>
    </div>
    <div :id="chartID"/>
  </div>
</template>

<script>
import echarts from 'echarts'

export default {
  props: {
    // {name,code,value,color}
    province: {
      type: Object,
      default: null
    }
  },
  data() {
    return {
      chart: null,
      mapOption: null,
      dataList: [],
      loading: false
    }
  },
  computed: {
    chartID() {
      return `chart_${this._uid}`
    }
  },
  watch: {
    '$props.province': {
      handler(newer, older) {
        this.initEchartMap(newer)
      },
      deep: false
    }
  },
  mounted() {
    this.initEchartMap(this.province)
  },
  methods: {
    // 初始化中国地图
    initEchartMap(province) {
      if (!province) {
        return
      }
      try {
        this.loading = true
        if (this.chart) {
          this.chart.dispose()
        }
        const mapDiv = this.$el.querySelector(`#${this.chartID}`)
        this.chart = echarts.init(mapDiv)
        const { name, code } = province
        if (code) {
          const existsMap = echarts.getMap(name)
          console.log('existsMap', existsMap)
          if (!existsMap) {
            const jsonMap = require(`echarts/map/json/province/${code}.json`)
            if (jsonMap) {
              echarts.registerMap(name, jsonMap)
            } else {
              this.$message.error('未获取到地图数据')
            }
          }
        }
        this.setMapOption(province)
        this.setMapData()
        this.chart.setOption(this.mapOption)
        // 钻取事件
        this.bindDrillDown()
        this.loading = false
      } catch (err) {
        this.loading = false
        this.$message.error(err.message)
      }
    },
    // 点击钻取下级
    bindDrillDown() {
      this.chart.on('click', params => {
        if (params.seriesType === 'map') {
          this.$emit('drilldown', { ...params.data })
        }
      })
    },
    backToChinaMap() {
      this.$emit('backToChina')
    },
    // 修改echart配制
    setMapData() {
      this.mapOption.series[0]['data'] = []
    },
    // 切换配置
    setMapOption(province) {
      const { name, color } = province
      const options = {
        title: {
          text: name,
          textAlign: 'center',
          textStyle: {
            fontSize: 14,
            fontWeight: 'bold'
          },
          left: 'center',
          top: 20
        },
        geo: {
          map: name,
          scaleLimit: {
            min: 1,
            max: 2
          },
          zoom: 1,
          top: 40,
          label: {
            normal: {
              show: true,
              fontSize: 12,
              color: '#333'
            }
          },
          itemStyle: {
            areaColor: color,
            opacity: 0.3
          },
          emphasis: {
            itemStyle: {
              opacity: 1
            }
          }
        },
        series: [
          {
            name: '突发事件',
            type: 'map',
            geoIndex: 0,
            // showLegendSymbol: true,
            data: []
          }
        ]
      }
      this.mapOption = options
    }
  }
}
</script>

<style rel="stylesheet/scss" lang="scss" scoped>
  #province_map_box {
      height: 100%;
      position: relative;
      &>div{
        height: 100%;
      }
  }
</style>

