<!--
 * @Description:
 * @Version: 1.0
 * @Autor: Luan Feng
 * @Date: 2021-02-08 15:57:24
 * @LastEditors: Luan Feng
 * @LastEditTime: 2021-02-08 16:55:23
 * @Tool: Auto Generated by koroFileHeader
-->
<template>
  <div class="card-wrapper">
    <div class="header">
      <i class="icon" :class="iconClass" />
      <span class="title">{{ headTitle }}</span>
      <span class="detail-link">
        <span>详情</span><i class="el-arrow-right" />
      </span>
    </div>
    <div class="content">
      <div v-for="(item,idx) in dataContent" :key="idx" class="item" :style="getItemWidth(item)">
        <div class="name">
          {{ item.name }}
        </div>
        <div class="value">
          {{ item.value }}<span>{{ item.unit }}</span>
        </div>
      </div>
      <div />
    </div>
  </div>
</template>

<script>
export default {
  props: {
    iconClass: {
      type: String,
      default: ''
    },
    headTitle: {
      type: String,
      default: ''
    },
    content: {
      type: Array,
      default: () => { return [] }
    }
  },
  data() {
    return {
      dataContent: []
    }
  },
  mounted() {
    this.dataContent = this.content
    console.log('datacontent', this.dataContent)
  },
  methods: {
    getItemWidth(item) {
      if (item.width) {
        return { width: item.width }
      }
      return { flex: 1 }
    }
  }
}
</script>
<style rel="stylesheet/scss" lang="scss" scoped>
.card-wrapper{
  .header{
    border-bottom: 1px solid #ddd;
    height: 28px;
    font-size: 18px;
    position:relative;
    padding:8px;
    .detail-link{
      color:blue;
      cursor: pointer;
      font-size: 12px;
      position:absolute;
      top:20px;
      right:4px;
    }
  }
  .content{
    display: flex;
    margin-top: 16px;
    .item{
      text-align: center;
      .name{
        font-size: 14px;
        font-weight: 400;
        color: #999999;
        line-height: 21px;
        letter-spacing: 1px;
      }
      .value{
        font-size: 28px;
        font-weight: 500;
        color: #333333;
        line-height: 42px;
        letter-spacing: 1px;
        &>span{
          font-size: 14px;
        }
      }
    }
  }
}
</style>
